site_name: ENGR-1330 Fall 2021
# navigation/site structure 
nav:
  - Home: index.md
#  - About: about.md
  - Syllabus : 0-Syllabus/ENGR-1330-2021-1-Syllabus.md
  - Lessons and Labs :
      - Introduction:
          - Computational Thinking and Data Science : 
              - Lesson 0: 1-Lessons/Lesson00/lesson0.md
              - Laboratory 0: 8-Labs/Lab0/Lab0_Dev.md
          - Problem Solving with Computational Thinking: 
              - Lesson 1: 1-Lessons/Lesson01/lesson1.md
              - Laboratory 1: 8-Labs/Lab1/Lab1_Dev.md
      - Programming Fundamentals:
          - Arithmetic : 
              - Lesson 2: 1-Lessons/Lesson02/lesson2.md
              - Laboratory 2: 8-Labs/Lab2/Lab2_Dev.md
          - Data Structures : 
              - Lesson 3: 1-Lessons/Lesson03/lesson3.md
              - Laboratory 3: 8-Labs/Lab3/Lab3_Dev.md  # need a new lab move this to lab4
          - Flow Control Structures : 
              - Lesson 4: 1-Lessons/Lesson04/lesson4.md
              - Laboratory 4: 8-Labs/Lab4/Lab4_Dev.md # move to lab 6
          - Data Files : 
             - Lesson 5: lesson0/lesson0.md
             - Laboratory 5: 8-Labs/Lab5/Lab5_Dev.md #need to rewrite 
          - External Functions and Modules : 
             - Lesson 6: lesson0/lesson0.md   
             - Laboratory 6: 8-Labs/Lab6/Lab6_Dev.md
          - Data Structures using NUMPY : 
             - Lesson 7: 1-Lessons/Lesson07/lesson6.md 
             - Laboratory 1: 8-Labs/Lab7/Lab7_Dev.md
          - Data Frames using PANDAS : 
              - Lesson 8: 1-Lessons/Lesson08/lesson7.md
              - Laboratory 8: 8-Labs/Lab8/Lab8_Dev.md
          - Data Display using MATPLOTLIB : 
              - Lesson 9: 1-Lessons/Lesson09/lesson8.md
              - Laboratory 9: 8-Labs/Lab9/Lab9_Dev.md
      - Engineering Computation :  # exam 1
          - Implicit Equations : 
              - Lesson 10: 1-Lessons/Lesson10/lesson10.md
          - Interpolation, Integration, and Differentiation : 
              - Lesson 11: 1-Lessons/Lesson11/lesson11.md
          - Linear Equation Systems : 
              - Lesson 12: 1-Lessons/Lesson12/lesson11.md      
          - Non-Linear Equation System : 
              - Lesson 13: 1-Lessons/Lesson13/lesson12.md       
      - Data Models and Decisions :
          - Models and Causality : 
             - Lesson 14: lesson0/lesson0.md
          - Descriptive Statistics : 
             - Lesson 15: lesson0/lesson0.md
          - Probability Distributions : 
             - Lesson 16: lesson0/lesson0.md
          - Probability Estimation Models : 
             - Lesson 17: lesson0/lesson0.md
          - Hypothesis Testing : 
             - Lesson 18: lesson0/lesson0.md 
          - Interval Estimates : 
             - Lesson 19: lesson0/lesson0.md 
      - Prediction Engines:     # exam 2
          - Visual Model Fitting : 
             - Lesson 20: lesson0/lesson0.md
          - Least Squares (Regression) Model Fitting : 
             - Lesson 21: lesson0/lesson0.md
          - Prediction Interval Estimates : 
             - Lesson 22: lesson0/lesson0.md         
          - Logistic Regression : 
             - Lesson 23: lesson0/lesson0.md
      - Classification Engines:
          - K Nearest Neighbor : 
             - Lesson 24: lesson0/lesson0.md     # exam 3
          - Support Vector Machines : 
             - Lesson 25: lesson0/lesson0.md
          - Artifical Neural Networks : 
             - Lesson 26: lesson0/lesson0.md
# nesting as pulldown??
  - Homeworks/Project:
     - Exercise Set 1: 2-Homework/ES1/es1-deploy.md
     - Exercise Set 2: 2-Homework/ES2/es2-deploy.md
     - Exercise Set 3: 2-Homework/ES3/es3-deploy.md
     - Image Classification Project (under development): 6-Projects/P-ImageClassification/MyANN.md
     - Instrument Calibration Project (reference links need update) : 6-Projects/P-InstrumentCalibration/InstrumentCalibration-Project.md
     - Music Classification Project (reference links need update) : 6-Projects/P-MusicClassification/genre-classification-project-problem.md
     - Concrete Strength Prediction Project (reference links need update): 6-Projects/P-ConcreteStrength/ConcreteStrength-Project.md
     - Audio File Analysis Project (under development) : 6-Projects/P-DTMF/DTMF-Part1.md
     
# active theme (mkdocs/readthedocs are free, they work differently wrt code blocks)
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python

# extensions to enable nice typesets 
markdown_extensions:
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code # easier than indenting
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js  # this file needs to be in the docs directory for site build