site_name: ENGR-1330 Example Course
# navigation/site structure 
nav:
  - Home: index.md
#  - About: about.md
  - Syllabus : 0-Syllabus/ENGR-1330-2021-1-Syllabus.md
  - Lessons :
      - Lesson 0 : 1-Lessons/Lesson01/lesson0.md
      - Lesson 1 : 1-Lessons/Lesson02/lesson1.md
      - Lesson 2 : 1-Lessons/Lesson03/lesson2.md
      #- Lesson 3 : 1-Lessons/Lesson04/lesson3.md
      - Lesson 4 : lesson0/lesson0.md
      - Lesson 5 : lesson0/lesson0.md      
      - Lesson 6 : 1-Lessons/Lesson07/lesson6.md      
      - Lesson 7 : 1-Lessons/Lesson08/lesson7.md
      - Lesson 8 : 1-Lessons/Lesson09/lesson8.md
      - Lesson 9 : 1-Lessons/Lesson10/lesson9.md
      - Lesson 10 : 1-Lessons/Lesson11/lesson10.md
      - Lesson 11 : 1-Lessons/Lesson12/lesson11.md      
      - Lesson 12 : 1-Lessons/Lesson13/lesson12.md       
      - Lesson 13 : lesson0/lesson0.md
      - Lesson 14 : lesson0/lesson0.md
      - Lesson 15 : lesson0/lesson0.md
      - Lesson 16 : lesson0/lesson0.md
      - Lesson 17 : lesson0/lesson0.md      
      - Lesson 18 : lesson0/lesson0.md       
      - Lesson 19 : lesson0/lesson0.md
      - Lesson 20 : lesson0/lesson0.md
      - Lesson 21 : lesson0/lesson0.md
      - Lesson 22 : lesson0/lesson0.md
      - Lesson 23 : lesson0/lesson0.md      
      - Lesson 24 : lesson0/lesson0.md       
  - Laboratory :
      - Lesson 24 : lesson0/lesson0.md 
  - Homework :
      - Lesson 24 : lesson0/lesson0.md       
      
     
# nesting as pulldown??

# active theme (mkdocs/readthedocs are free, they work differently wrt code blocks)
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python

# extensions to enable nice typesets 
markdown_extensions:
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code # easier than indenting
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js  # this file needs to be in the docs directory for site build