site_name: ENGR-1330 Example Course
# navigation/site structure 
nav:
  - Home: index.md
#  - About: about.md
  - Syllabus : 0-Syllabus/ENGR-1330-2021-1-Syllabus.md
  - Topics :
      - Introduction:
          - Computational Thinking and Data Science : 1-Lessons/Lesson00/lesson0.md
          - Problem Solving with Computational Thinking: 1-Lessons/Lesson01/lesson1.md
      - Programming Fundamentals:
          - Arithmetic : 1-Lessons/Lesson02/lesson1.md
          - Data Structures : 1-Lessons/Lesson03/lesson2.md
          - Flow Control Structures : 1-Lessons/Lesson04/lesson3.md
          - Data Files : lesson0/lesson0.md
          - External Functions and Modules : lesson0/lesson0.md      
          - Data Structures using NUMPY : 1-Lessons/Lesson07/lesson6.md      
          - Data Frames using PANDAS : 1-Lessons/Lesson08/lesson7.md
          - Data Display using MATPLOTLIB : 1-Lessons/Lesson09/lesson8.md
      - Engineering Computation :
          - Implicit Equations : implicit_equations/NewtonsMethod.md
          - Interpolation, Integration, and Differentiation : integration_differentiation/numerical_integration.md
          - Linear Equation Systems : 1-Lessons/Lesson12/lesson11.md      
          - Non-Linear Equation System : 1-Lessons/Lesson13/lesson12.md       
      - Data Models and Decisions :
          - Models and Causality : lesson0/lesson0.md
          - Descriptive Statistics : lesson0/lesson0.md
          - Probability Distributions : lesson0/lesson0.md
          - Probability Estimation Models : lesson0/lesson0.md      
          - Hypothesis Testing : lesson0/lesson0.md       
          - Interval Estimates : lesson0/lesson0.md
      - Prediction Engines:
          - Visual Model Fitting : lesson0/lesson0.md
          - Least Squares (Regression) Model Fitting : lesson0/lesson0.md
          - Prediction Interval Estimates : lesson0/lesson0.md
          - Classification vs. Prediction : lesson0/lesson0.md      
          - Logistic Regression : lesson0/lesson0.md 
      - Classification Engines:
          - K Nearest Neighbor : lesson0/lesson0.md
          - Support Vector Machines : lesson0/lesson0.md
          - Artifical Neural Networks : lesson0/lesson0.md       
# nesting as pulldown??

# active theme (mkdocs/readthedocs are free, they work differently wrt code blocks)
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python

# extensions to enable nice typesets 
markdown_extensions:
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
  - fenced_code # easier than indenting
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js  # this file needs to be in the docs directory for site build